---
name: 'Release Formatting'
on: [ push ]

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build source artifact
        run: mkdir -p rocky-logos-83.0 && cp -r . rocky-logos-83.0 && tar cfj rocky-logos-83.0 rocky-logos-83.0.tar.xz
      - name: Publish artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: rocky-logos-83.0.tar.xz
          path: rocky-logos-83.0.tar.xz
