---
name: 'Release Formatting'
on:
  push:
    tags:
      - '*'

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build source artifact
        run: |
          mkdir -p ../rocky-logos-${GITHUB_REF##*/} &&
          cp -r . ../rocky-logos-${GITHUB_REF##*/} &&
          mv ../rocky-logos-${GITHUB_REF##*/} . &&
          tar cfj rocky-logos-${GITHUB_REF##*/}.tar.xz rocky-logos-${GITHUB_REF##*/}
      - name: Publish artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: rocky-logos-${GITHUB_REF##*/}.tar.xz
          path: rocky-logos-${GITHUB_REF##*/}.tar.xz
      - name: Generate release
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT_RELEASE: "false"
          PRE_RELEASE: "false"
          CHANGELOG_FILE: "none"
          ALLOW_EMPTY_CHANGELOG: "false"
          ALLOW_TAG_PREFIX: "true"
        with:
          args: |
              rocky-logos-${GITHUB_REF##*/}.tar.xz
